### ISSUE TITLE
Colour example

### ISSUE THREAD

**Issue by adriangrepo** [tgsmith61591/smrt#11]
Do you have an example for using smrt with RGB pictures? - 

When creating my training dataset as per below with RGB images

```
img = pil_image.open(im_file)
X[index,:] = np.array(img)[:,:,0:3]
```

I get an error thrown in base.py check_array()
`
ValueError: Found array with dim 4. Estimator expected <= 2.`

**Comment by tgsmith61591** [comment]
That's probably a result of [this line here](https://github.com/tgsmith61591/smrt/blob/master/smrt/autoencode/autoencoder.py#L540). Under the hood, the auto encoder is calling the scikit-learn `check_array` function. You could probably get around that (if you forked) by setting `ensure_2d=False`

**Comment by adriangrepo** [comment]
Thanks,

I bypassed check_array but then run into another issue in autoencoder.py in _initialize_graph(self, X, y, seeded_random_state)

```
 def _initialize_graph(self, X, y, seeded_random_state):
    # validate X, then make it into TF structure
     n_samples, n_features = X.shape #wants 2 values to unpack
```
I then tried an alternative method - when reading in images:

```
X = np.zeros([len(df), 128*128*3])
    ...
    for im in folder:
        img = pil_image.open(im)
        X[index,:] = np.array(img).flatten()
        ...
```

create fakes then:

`npim=np.reshape(fake, (128,128,3))`

But am getting meaningless vertical stripes only for resultant fakes...

**Comment by tgsmith61591** [comment]
I didn't design or test this on RGB images, it was really originally intended for 2d matrices. I demoed on MNIST because it was easy to qualitatively validate. If you're wanting to adapt to N-d matrices you may have to do a bit of finagling... Would love to see what you come up with

**Comment by adriangrepo** [comment]
I tried just converting my images to greyscale then running, but I need to work out why I am just getting nan output. 
I tried on a reasonable size training set 10,000 images but keep getting cost=nan when creating vae with v_encoder.fit(X_train) .

Closing this for now.
