### ISSUE TITLE
[REQUEST FOR MERGE]Difference in encoding codec used by Python 3 pickle

### ISSUE THREAD

**Issue by hasibzunair** [tgsmith61591/smrt#12]
```
def _load_from_pickle():
    with open(fl, 'rb') as f:
        d = pickle.load(f)

UnicodeDecodeError: 'ascii' codec can't decode byte 0x90 in position 614: ordinal not in range(128)
```
Not compatible with Python 3. I made a fix for this. Should I send a PR?

**Comment by tgsmith61591** [comment]
This *should* be compatible w python 3. Definitely submit your PR but without context here it's hard to know the true source of the problem

**Comment by hasibzunair** [comment]
Please check [#13](https://github.com/tgsmith61591/smrt/pull/13).
